name: OpenVPN

on:
 # schedule:
  #  - cron: '0 */3 * * *' #Configuré pour l’obtenir automatiquement toutes les 3 heures

  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: config
        run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
        
      - name: Installer yt-dlp
        run: |
         sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
         sudo chmod a+rx /usr/local/bin/yt-dlp

        
      - name: Installer OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
         
      - name: Configurer le fichier ovpn
        run: |   
         sudo openvpn --config ${GITHUB_WORKSPACE}/vpn/client.ovpn --auth-user-pass ${{ secrets.CLIENT_CONNECT }}
       #   username: ${{ secrets.CLIENT_ID }}
         # password: ${{ secrets.CLIENT_MP }}
          
  #    - name: Connecter le VPN
  #      uses: "kota65535/github-openvpn-connect-action@v2"
   #     with:
  #        config_file: client.ovpn
  #        username: ${{ secrets.CLIENT_ID }}
  #        password: ${{ secrets.CLIENT_MP }}
      - name: essai1
        run: |
         touch ./essai1.m3u8
         sudo cat >./essai1.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.dailymotion.com/video/x2j4lj9)
         https://raw.githubusercontent.com/BG47510/Zap/main/assets/error.m3u8
         EOL

      - name: git add
        run: |
         git add -A
         ls -la

      - name: commit & push
        run: |
         git commit -m "Les liens sont mis à jour"
         git push

      - name: Déconnecter le VPN
        if: always()
        run: |
          sudo killall openvpn
