name: OpenVPN

on:
  workflow_dispatch:
  
  jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: config
        run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
        
      - name: Installer yt-dlp
        run: |
         sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
         sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Installer OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connecter le VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ${GITHUB_WORKSPACE}/vpn/client.ovpn
          username: ${{ secrets.CLIENT_ID }}
          password: ${{ secrets.CLIENT_MP }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Couper la connexion VPN
        if: always()
        run: |
          sudo killall openvpn
